# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 22a64dbffb49c3e43bd61f98387393fa2e57d2ae42e6959f930ef7700882d3deb42045a286fc4da13e42844f2edca9edeb0b95d36a4254ea53a87f848861fdbe

test:
  secret_key_base: ad658de76429feb8de49bae4e356c8c114002cad90e85633a72bb7496e9ba2e512d617b5cdc95f31f0b3ccf6c37aa045d5615de94131d7ab44088002f079f5c5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
